### ISSUE TITLE
Support for ds3

### ISSUE THREAD

**Issue by eletrolitico** [kenshaw/motionserver#1]
I think it's possible to easily add support for DualShock 3, i messed around with your code a bit and figured out the id for DS3 is 616 and if I remove the axis verification part it (kind of) works, it's a bit laggy
It would be nice if you officially supported it

**Comment by kenshaw** [comment]
Sure -- please submit a PR, glad to merge. I don't have a DS3 controller to test with, but yes, I believe it would work the same.
