### ISSUE TITLE
ERROR: invalid message: invalid request length

### ISSUE THREAD

**Issue by DocMAX** [kenshaw/motionserver#3]
I get this error while playing. DS3 controller.

**Comment by kenshaw** [comment]
This was built for a DS4 controller. I don't have a DS3 controller to test
with. I'd appreciate a PR if you're able to figure out the issue.

**Comment by qurious-pixel** [comment]
I receive the same error with DualShock V1. `dualShock4_v1 = 1476`
The command I used was `motionserver -l 127.0.0.1:27261`
With the default port no text is shown.

<details>
  <summary>Error Message</summary>
 
![udp-server](https://user-images.githubusercontent.com/62252937/109089319-e48cce00-76c5-11eb-9533-b8a28d9ec9d4.jpg)

</details>
